[
  ./files.nix
  ./home.nix
  ./programs/dolphin.nix
  ./programs/fzf-tab-completion.nix
  ./programs/glab.nix
  ./programs/goto.nix
  ./programs/kmail.nix
  ./programs/konsole.nix
  ./programs/less.nix
  ./programs/merkuro.nix
  ./programs/okular.nix
  ./programs/plasma.nix
  ./programs/shellcheck.nix
  ./programs/signal-desktop.nix
  ./programs/slack.nix
  ./programs/taskell.nix
  ./programs/yamllint.nix
]
