#!/usr/bin/env bash

# Recursively find images below a certain resolution
#
# Usage: find-lowres [-r] [directory [dimension]]
#
# directory defaults to . (the current working directory),
# dimension defaults to 1000x800 pixels
#
# With -r: removes images instead of just listing them. Use at your own risk.

while true; do
    case $1 in
    -r | --remove)
        action='--action=rm %F'
        ;;
    - | --)
        shift
        break
        ;;
    -*)
        echo "Error: unknown option: $1" >&2
        exit 1
        ;;
    *)
        echo "Error: unknown argument: $1" >&2
        exit 2
        ;;
    esac
    shift
done

dir="${1:-.}"
dimension="${2:-1000x800}"

feh --recursive --list --verbose --max-dim "$action" "$dimension" "$dir"
