[
  ./modules/cdhist.nix
  ./modules/dircolors.nix
  ./modules/firefox.nix
  ./modules/fzf.nix
  ./modules/fzf-tab-completion.nix
  ./modules/gcc.nix
  ./modules/git/default.nix
  ./modules/goto.nix
  ./modules/grep.nix
  ./modules/less.nix
  ./modules/kubectl.nix
  ./modules/nix.nix
  ./modules/shellcheck.nix
  ./modules/starship.nix
  ./modules/taskell.nix
  ./modules/yamllint.nix
  ./modules/zsh/default.nix
  ./modules/zsh/vimMode.nix
]
