[
  ./programs/cdhist.nix
  ./programs/dircolors.nix
  ./programs/firefox.nix
  ./programs/fzf.nix
  ./programs/fzf-tab-completion.nix
  ./programs/gcc.nix
  ./programs/git/default.nix
  ./programs/goto.nix
  ./programs/grep.nix
  ./programs/less.nix
  ./programs/kubectl.nix
  ./programs/nix.nix
  ./programs/shellcheck.nix
  ./programs/starship.nix
  ./programs/taskell.nix
  ./programs/yamllint.nix
  ./programs/zsh/default.nix
  ./programs/zsh/vimMode.nix
]
