deepl_api_token: ENC[AES256_GCM,data:R1D7HtXNQLJxxAC/fkGWRPxJ2TzJsyRbvLqa3i4dCl4Pse6YgCWf,iv:BJnzkMScu64VMwC74J4mHG29IyT85/muUyX8Kp50ksA=,tag:P6Ch2pQ6D/59DHiZGLCqDA==,type:str]
github_api_token: ENC[AES256_GCM,data:LyS2r1iytZ2Gf1HuyRGOIgBWNhoF0WJQqtpGgrNIsApdkD2siQaHxw==,iv:LcnloQ5/RpzC0uDp7KMeVqlt6E8xZhdPAGmCandbVoc=,tag:DxQx0nIMaN1PEo+0bnv66Q==,type:str]
firefox_extensions:
    keepassxc-browser: ENC[AES256_GCM,data:zaZIq7ZoqOjlPuFYPHspLnoep7bUJYm5SKWi21fv5YFDxJlFwvCqv3c0HTXEIZYQKIDyW/evg19kE1v0EtRIXJPTcBc4uU9e2mPbcryyK5lzN9oGRSU5SBKrEbg8wm2BJ1J+Euou9foj/eFlNW1Uqkl37axdMga/vH4yPhwhfiCxwFZnl++wnBe5u84Fl5Y+I7GzNIwaWasLITx0e57PyW06cRy1A/SYF5upo99k92//9xWNRHOhx2J2DBmapi/rCt5aoprU8UisGC722axlbmqKz0KCuaV/+UcDLKFIyBTC8UiE3fdd3w==,iv:at7/TWwXGiMELdvxmhG+HUiaqzcoEBe/EMOyUb/Pok8=,tag:mc1TW/57lWGidam0kZxxOw==,type:str]
    simple-translate: ENC[AES256_GCM,data:eFA2Fx7OBit+HYcNGDasTXxHzwxfgQKkCOYNV9hTJ8Wt1R0BJHXQyeiznmdrgFxWejkK5xjx/1ZbooCTwTr+g/j2,iv:5vEBHG83hvh9MEbqIUam1LZ12yYyitkqr0IQkmqjDUg=,tag:IeQoCp1fDHhZ/5CDNrA4/g==,type:str]
    tab-session-manager: ENC[AES256_GCM,data:HHQMsDi0s92R3+OuL160tVOGDV2cqZ1DsNM0ySdW2vRyUk61AbTgPR61CqZ6aQaHv6G3N/yiLX/3vrJmG4w66tK+Vq5W9sMaOwUv7S2T8GgFHcSbj5iCKA5D4kPV8yAIXPVLruEva0rAGPzcwzz/9aikpR0NBVe5S/oVDV1oVEzXvHurDTFO5jHedeB1cUWJQTIwSg4Z4a8r+TYL4EU2/zwT049ZFGG77EKyGpC3KPV1cgDX/Hx9/ES2g+SqCFsiEx5VB7MueH7qQRLhXlAWDqM6Px4h57LI8n2sLjcEdhYW+MwAG5K/6dyUpNZLSXG7A3L9MbLSsPYOkp2siZHJ6Mje5zS2lwbSighNAtgwly3UZg/tY97H7enS3pqVqvSKW5l6EEJSnjn/c9133sbHSZKsBKNMlGK81teApQseATQHhJlloEsWEKFan9T/l36M+GUhhW+WctsHvZyyOXjlV7mm8huvuIaudI276moPLWYiBfD6YaJ0w5ZEb6XwEb3HcFxlTrpY1GWWG+r838zFQ9yRE7DDA+3pR3R8TVzlrJZWZx4mWifcTMIMMg8sEJqLhbVF1Qbqa6Sxaec=,iv:yhvzbwLcQenuLDa1HZwHVBiR0dagyqIgN5O6bL65arM=,tag:zSazweo7an4riMT9ndcBjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxd0RXaTR2V1dVQklTLzFW
            cDZpa3RrUzZVTG5hVnNaZHZmZzJlckNvdmhZCnV5QUtSMjY1cGJyaDRESzlxSWZK
            VmZUcHp2bVlVcGdISGdCUU1JY01rUDQKLS0tIHRDK0tsNytoQWhVVk1IVWNFQVp2
            aWpRVXJncDl3dTh2aitPOWg3VXU5aUEKfFpung5n7Imd+J2iOQKwRRHhOJoICaEK
            ymfQvMrmubx0STxdtCVClay/+G9c6Vwk/HJ7ehWRVcP6FEdLQGtS4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wadrydzchtpz9flzy7geszrcupald64v9zl8cyr2e2r2cr8rwgxq0lvfjg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxckFWNEt6NEI0WFFTeTBE
            N205YzlBaFNNNnZ2UnFGYlFnSzJFb2V4b0hzCnozTmlTT20yRFRzU082cmthV3hq
            djUvbnhBczVEVkx6aGZsd0R2ZlV4dW8KLS0tIHlBbUZNN0xtaTBjZGhiWDdWdkhk
            ZTRDaDh6cUpGTDFlVWFoVlZFRWhGbkEKfuDExmakJE9Yx0irpbAqZqxE0g1D4TuO
            rswKyRt+Oa5IpLyc8GLDxN0n5N3f1iYCIeNa/jLjRy0PC90wZ1KxAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jyazkguk47p46qaatr6avlexslu7amfra690f7jpwq55l2t6p5hqz67q7j
    lastmodified: "2026-06-09T08:06:29Z"
    mac: ENC[AES256_GCM,data:Gv17feC+fg7k6PBCrIxmky0cDr9o7d0UXw69xQe+aPNbUc2q8Z10kEqT/lh6VuqwUe0shm/3IKTSiiGvS2sK/+lU+kTBPLB5ApuHhbjpLAbG7GLRdiKU/wiYjWkQpUR8/DCtMNdHADIMjUHeQoLVWUjEBrHSD5vMbivEVs1rwFg=,iv:I/TTdTXXLdfnx8btD3haCUkJFhcbzsQWLkDIGyDd/Xs=,tag:CTud74go5Rg6c4ioHfsPTg==,type:str]
    pgp:
        - created_at: "2026-03-11T11:44:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hH4DJBGmhVjpZEASAgMEy8zDWZoHtrJcMjGpebkgtpWqf+2qDVgiC886Hk8Od8Og
            jRY0dUAb2ptfIFZHwp7AYAaECkYpWTeSlwZ/zJ/tujA+AwAcEsWqN83WxEX49Gp2
            UI/AiWo/CC5qfsH60ozhcKtBRVPE460A2vRGYJFBv/DSXAEKMkqMNR7CKGOuVZ/z
            NJL4BkRZSnJsCAfR+vtcISYRf/b4NxFiO9tyg6CnDXiWQJCDg/2AQMqi1dDvWwXE
            MFdphKYQBYcVo/r167OpKmZLWFDlPJDoFvtQn5oP
            =rMoc
            -----END PGP MESSAGE-----
          fp: 744A942D0348D4EC23F9339FE5231FEFFA0D518C
    unencrypted_suffix: _unencrypted
    version: 3.13.1
