#!/usr/bin/env bash

# Terminate already running dunst instances
killall --quiet dunst

# Wait until the processes have been shut down
while pgrep --euid $UID --exact dunst >/dev/null; do sleep 1; done

dunst &
echo "Dunst launched..."
