#!/usr/bin/env bash

# Terminate already running picom instances
killall --quiet picom

# Wait until the processes have been shut down
while pgrep --euid $UID --exact picom >/dev/null; do
    sleep 1
done

# Launch picom, using default config location ~/.config/picom/config
picom --daemon

echo "Picom launched..."
