hashed_password: ENC[AES256_GCM,data:p0WDwZkuQhALgeQ+nQlF7LiYyqDNNrfPIYPWbQFWJ4KOCwn9DVAdu5LuflO5LSK7olm2ePfs1GDnDhH4uSAB67emuGRjK39PUw==,iv:SZ2DbuNuQjAUFbGHNcx0tmxBHQBejk1fg+M5GkQ74UI=,tag:meosgBcY/O7Af6fu1/rHhg==,type:str]
sops:
  age:
    - recipient: age1ftlc54g0t5uqj8nce0s63m860l925vckm08zhmksjzc6yja0metq2778zr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVzYrbmFObW5LQmRLNlU3
        USt2c0c1OUk2Nll1cEd6QTEvdDhLVElIbHk4CmRvR3FYczA0U1B5SHRFdEpXOENh
        ZWpBcGRucGJxZkp0b0cyckhiODVoV1UKLS0tIGdnbjEzMHVMeDNvZWpoakpMMUls
        bHJiUDdGRFNmZmx6MUM4YVY2UWhVV1UKnYfaZj/ZnBU1R72Za3D9nZtwVSF45r4P
        nep2a+TNW7BkrKVZp/JbIqlpQnSMtIIGmyax87wbTJREfzQBG1Txsw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1jyazkguk47p46qaatr6avlexslu7amfra690f7jpwq55l2t6p5hqz67q7j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTV2t3akFOUVN4SEExbXVz
        SEFubGxzMDNHWkpiaVo0SEkrdEt0OWs5UGw0CkFOcmZ6VGVnanN5ZFNNMm5HOE0v
        VWtMOU44VDhzeTJVeUdHS2Zudm1XWXcKLS0tIDNONUJBeVNpaUJERkZpNjVRdGpW
        c0YwcngxdHdwOXBpYWFoWlZKajdLUWcKXOQHF77pn2w4yG/k6cobvm8yJFgbBhQq
        kxB2VQiVTOTpSeG2zGJFFn1Ba2EZkDDhZZ0lT2dI3PPRM50f5+awgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-29T08:14:35Z"
  mac: ENC[AES256_GCM,data:A9IWF1vbuNU1PQL1q6mousChyerARvAPlEPwezCdT634XlwN42gBBYZuBEfkPGErDTMX3+JxKPDfu8jgSWdXvS7uUBXxZNO/hm2Xamf46DzHQJrE4hVyQZA3KS6u8cfHD1woEoTsJKDp8vLyx5aIcSmRRr+BgzrmX9ObDw+GojE=,iv:JK/Cc9nMxnCetNqwquROKvw8TGMorwx42t5x622FL8M=,tag:jjaUEpNv94GmPIO1hAhZUA==,type:str]
  pgp:
    - created_at: "2025-06-06T13:48:52Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DM8dcuKjdXWESAQdA3CHDZ/5+JYuGsZepjbSlVnXvH85FsKED4sKYCgIQFjUw
        XouKm/LE1CQOrXSDd55pP0DjW0Kxuiv6tTGIqNlgR/n65w7/bbqyUBSx4CCIvb7K
        0l4BJZAngY78FZXNgoRK8L1Z9HhZKwMF0neXpHf82zB2PwXcnwgyg1kXiRv55wSf
        AmD0aky+wbuFeixYcLxI3G+Q1tIqNRJeMKEMXo/TsFMI8Yr0ciPu/xJF+L5jSEwy
        =UMkF
        -----END PGP MESSAGE-----
      fp: 4D6B62168F6FFE33B8420BCBED7FCB814CB6C157
  unencrypted_suffix: _unencrypted
  version: 3.10.2
