hashed_passwords:
  bmr: ENC[AES256_GCM,data:R0pUMhWvuPf3tQ3K7JbuCq5nvezlIMeoi/nLvuAbz+/fWWmWv63mZQkxf8ibNxoXSVvgzM7nfN+1dKjvoZKoHd+kZ/5S+ZER4g==,iv:uCRG/m4DGUY5+6AXB0AXFdIPf3nfT2Z/fdCKvWvqOKE=,tag:+nqxmqYaWEsrhm4mW/irWA==,type:str]
  root: ENC[AES256_GCM,data:Gdt8ufKKhR0QPPAgojdgWCZ8lrInhJ1d29p6xhoIOM1t2WPTQ/yLFQLZyacIwx7+cKQ5KwSdn/Hi/C4vI9jkP/6oLoufFk5s4A==,iv:y5fKwle4S0AQf+wr810M87TsQNV7CvKiqdSr3IHhUNM=,tag:6sx1E1oTZvzad4hZE4VK5w==,type:str]
sops:
  age:
    - recipient: age1wadrydzchtpz9flzy7geszrcupald64v9zl8cyr2e2r2cr8rwgxq0lvfjg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TFNucEd4eXdsdVUvd3p0
        Vng4V2ZtcWQrSklOZ3o1ZjlzaDJ5WXBESFFZCm9lOThOY3EvQ0JIRklmSytGMFVt
        amFoY2FXMDhzNStER2Zyekp6K1BLKzgKLS0tIGpYSFE1eVZoNWo4djgxb3dESm1j
        S1JPMVJwNzZyclZhOHB2RkdxTUxOTWMK3Bt9qrjnFO1H9ZOdx82xBVl0ts99tQrA
        1B8k9pzq6Mh0a1lME3ouVQw+NGR3LTeKDj2Znb/jqIBEFNERB9Vdsw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1jyazkguk47p46qaatr6avlexslu7amfra690f7jpwq55l2t6p5hqz67q7j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VXIvdXF2bGJMK2c0OWZt
        d0NXRUhMeHE1ZVE4WFUvcFcvR1ZFZHZGWlE0CjJINDZSdmZOWEl4b0hoYjU2K0VB
        bWtHak5KRlZmQlFZZ21YbTdURnIzK1EKLS0tIEVIZk1QY1BLZ055TlRZWU55UnE2
        RTMzRWFQaGtXWFAvUmsvTktkVlNwTVkK2o0N7lvQK7DvVYtqZTDGH+qrLQFIsIJU
        1IBDEE3zMPJn/wuf/Jje8lJfPnNRQh7nJVTO/Jjtn1pcbzIeFr/P7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-13T18:27:09Z"
  mac: ENC[AES256_GCM,data:pHO5UK7++f6FS+Ahv/w/Bn9ptF1v5knL3Yq+s/XdukmTR7vc1yuJx8K0o6DyeThzfP3iciBtPf5HWcnmi8fdevqET/WhDMisPR42QR34IeoYgwHBZd8zgSVuGDP4aTK5jJBBIzU9Xc+dYORtwyJdI0/nLQVQwiGakP2mgZ2qD3U=,iv:XWNsWLJZdUvuOLpz2KAr9y7RXblqEur3RNP3CEW+t2A=,tag:9DjoqBeDhmrDzbF7NMpZXw==,type:str]
  pgp:
    - created_at: "2025-08-13T18:47:31Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DM8dcuKjdXWESAQdAwqPuZC548f6ygRrmorLTjWM39a+NzRJcrZczfAf/eR4w
        FWwfiwsw/X79C77ApnKwjplKPCsh1oVw7sJ5m5ZYtvm4HD/Afqyh0ErKNAjwO9ms
        0l4Bb96FzWsDPFnsBEMi2cOjPODkZQ48RKdDeaGYgDQqu+3pe5o9sBwJKJPkWr+z
        GmazklbrywETv50iN2GrEkN2lmnAfiiDTLMUwiX++9eE/bxfCgEbYZcpVZMUEs8i
        =W8H5
        -----END PGP MESSAGE-----
      fp: 4D6B62168F6FFE33B8420BCBED7FCB814CB6C157
  unencrypted_suffix: _unencrypted
  version: 3.10.2
