hashed_password: ENC[AES256_GCM,data:0kjAHHrW0LUoG2TKVqivtsSliJ/h82gvNldmIh/yutvwIwt+9QQ8kUW+/fCkBrdiw+smmTEZz805aARhAXQV6dXOSJjHvfqE0g==,iv:mxh18ezy2mMf8E2/h1voj5xbap69XsZUBY2xN6IOFsA=,tag:MT8UVMVNeFe4suKzyQ9RXg==,type:str]
sops:
  age:
    - recipient: age1wadrydzchtpz9flzy7geszrcupald64v9zl8cyr2e2r2cr8rwgxq0lvfjg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TFNucEd4eXdsdVUvd3p0
        Vng4V2ZtcWQrSklOZ3o1ZjlzaDJ5WXBESFFZCm9lOThOY3EvQ0JIRklmSytGMFVt
        amFoY2FXMDhzNStER2Zyekp6K1BLKzgKLS0tIGpYSFE1eVZoNWo4djgxb3dESm1j
        S1JPMVJwNzZyclZhOHB2RkdxTUxOTWMK3Bt9qrjnFO1H9ZOdx82xBVl0ts99tQrA
        1B8k9pzq6Mh0a1lME3ouVQw+NGR3LTeKDj2Znb/jqIBEFNERB9Vdsw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1jyazkguk47p46qaatr6avlexslu7amfra690f7jpwq55l2t6p5hqz67q7j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VXIvdXF2bGJMK2c0OWZt
        d0NXRUhMeHE1ZVE4WFUvcFcvR1ZFZHZGWlE0CjJINDZSdmZOWEl4b0hoYjU2K0VB
        bWtHak5KRlZmQlFZZ21YbTdURnIzK1EKLS0tIEVIZk1QY1BLZ055TlRZWU55UnE2
        RTMzRWFQaGtXWFAvUmsvTktkVlNwTVkK2o0N7lvQK7DvVYtqZTDGH+qrLQFIsIJU
        1IBDEE3zMPJn/wuf/Jje8lJfPnNRQh7nJVTO/Jjtn1pcbzIeFr/P7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-18T12:45:56Z"
  mac: ENC[AES256_GCM,data:M3YA1dKbqaR6vB0PLzlJC4lK5N64s8QE90I4+Gw26xJny3ZqBXdlzziXfbNaa5NMgqpFfjlXP6IxhNawwOr/euBJ/6+e7d4lwQjGUga6+C0AnilyIQW0G5yHTyV4/Q+pPdAQOPP847d1ufxOxE5dVQ57eVpYXTxwzt2SmjMjfks=,iv:sA8mckigq5ujUmmigYi5arWyubbw8EgXPSakRAYvVNQ=,tag:H0er5XXDHTb6o4OJ+HzU9w==,type:str]
  pgp:
    - created_at: "2025-08-13T18:47:31Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DM8dcuKjdXWESAQdAwqPuZC548f6ygRrmorLTjWM39a+NzRJcrZczfAf/eR4w
        FWwfiwsw/X79C77ApnKwjplKPCsh1oVw7sJ5m5ZYtvm4HD/Afqyh0ErKNAjwO9ms
        0l4Bb96FzWsDPFnsBEMi2cOjPODkZQ48RKdDeaGYgDQqu+3pe5o9sBwJKJPkWr+z
        GmazklbrywETv50iN2GrEkN2lmnAfiiDTLMUwiX++9eE/bxfCgEbYZcpVZMUEs8i
        =W8H5
        -----END PGP MESSAGE-----
      fp: 4D6B62168F6FFE33B8420BCBED7FCB814CB6C157
  unencrypted_suffix: _unencrypted
  version: 3.10.2
