hashed_password: ENC[AES256_GCM,data:p0WDwZkuQhALgeQ+nQlF7LiYyqDNNrfPIYPWbQFWJ4KOCwn9DVAdu5LuflO5LSK7olm2ePfs1GDnDhH4uSAB67emuGRjK39PUw==,iv:SZ2DbuNuQjAUFbGHNcx0tmxBHQBejk1fg+M5GkQ74UI=,tag:meosgBcY/O7Af6fu1/rHhg==,type:str]
sops:
  age:
    - recipient: age1tpm1qg43j96890nswz990yhfsdtn7n5lh2xcxjxpxnrwu8x328wzkh6e287ug0x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHRwbS1lY2MgN0RzMG5nIEF0ZDlEZWc0
        ajQ2c0dOUnlTK05xYmovRkxXTEFLV0VNRVNaQ0k2MEJTZjRNCnhIUVJOR2UzVi84
        RGdlMTBYY1d2L0oxTHZXQk1wVG9HUnBHTzVRSDR4KzAKLS0tIHhrZEtOUlpzQ2Yv
        RzE2Y2FqVnRIdU55Yy9HUUFnRlpucWhScHVQZDVBRFEK4SR3m62Ri4mW1i5+UbWF
        DL78/h4uZIvqFIt3ZMjdToaKQZeDMmZg9e3GvY/u5hd29Uc2EY1ONsNIhro9orUo
        sA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1jyazkguk47p46qaatr6avlexslu7amfra690f7jpwq55l2t6p5hqz67q7j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWT3VjM1NEdzZabU9pbElP
        a0N1WFFKSjN1TnlKZjBiYW12NU04VGRWanhvCmhXV3BweHF1K25MWmJZWmErTEJH
        RWV3ZTkyckFDcm5BVW11K3IvNkNlbEEKLS0tIHFFQVhIME5NcWErSGQ5ZEZZSU9S
        MzlYdlQrcitNYzVieG9XaThCdWZUR2sK5cd1VYKNWtoUCez/WfmRK793kFc40Utl
        AYOceviZ/tYlNC5DU3AuH8vjf2nplvNHtjxXdwhWMv5+K4mgPBqa7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-29T08:14:35Z"
  mac: ENC[AES256_GCM,data:A9IWF1vbuNU1PQL1q6mousChyerARvAPlEPwezCdT634XlwN42gBBYZuBEfkPGErDTMX3+JxKPDfu8jgSWdXvS7uUBXxZNO/hm2Xamf46DzHQJrE4hVyQZA3KS6u8cfHD1woEoTsJKDp8vLyx5aIcSmRRr+BgzrmX9ObDw+GojE=,iv:JK/Cc9nMxnCetNqwquROKvw8TGMorwx42t5x622FL8M=,tag:jjaUEpNv94GmPIO1hAhZUA==,type:str]
  pgp:
    - created_at: "2025-08-12T12:29:36Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DM8dcuKjdXWESAQdAS2DlrErJeTg3BeFD/NSkTttC8fEqIasElpdsXMSHVkgw
        hY7uRcd0IJHkeTSWDyRdCFVKlwfXISq9NxFGA4UJ6ir0RaFnTOnsvRWx3LqmuxzZ
        0l4BfLNuw9honT1yH6vrb5KVwhOhj4LGslQp+VFo73GzgDBTNBqzj9UUvBxWVHsO
        uw86CZ09j388tPvOHTHkLh0GrhDL4bk0INfBlJWom4RARqHPdjtpEz3PR5e6ZYjz
        =36xf
        -----END PGP MESSAGE-----
      fp: 4D6B62168F6FFE33B8420BCBED7FCB814CB6C157
  unencrypted_suffix: _unencrypted
  version: 3.10.2
