hashed_password: ENC[AES256_GCM,data:p0WDwZkuQhALgeQ+nQlF7LiYyqDNNrfPIYPWbQFWJ4KOCwn9DVAdu5LuflO5LSK7olm2ePfs1GDnDhH4uSAB67emuGRjK39PUw==,iv:SZ2DbuNuQjAUFbGHNcx0tmxBHQBejk1fg+M5GkQ74UI=,tag:meosgBcY/O7Af6fu1/rHhg==,type:str]
sops:
  age:
    - recipient: age1ftlc54g0t5uqj8nce0s63m860l925vckm08zhmksjzc6yja0metq2778zr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSzU3UXZqbS9mM09BYzdH
        S0hBWWNWaTFmUVExeG01cXUvall5cllsQ1NvClpYZUlsRzJCZWFlaXRjTTJtM0J1
        U2tCeUVpeUxjWXZoWGM2UTdKem05ckkKLS0tIE1QTHVFUVpvR1NpYjJ4Y2Zpb044
        STZyR3g3UDlEWHRaa29aekxrZGZGTmcKbUI/vp6g5ZYwFJ6iYUsSy+gyHeGDlWmy
        GqwVIp08EYbZ6nOtP83hu6dJF5oM0WLz3e0r+w2iuFulgWuCmPsLlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-29T08:14:35Z"
  mac: ENC[AES256_GCM,data:A9IWF1vbuNU1PQL1q6mousChyerARvAPlEPwezCdT634XlwN42gBBYZuBEfkPGErDTMX3+JxKPDfu8jgSWdXvS7uUBXxZNO/hm2Xamf46DzHQJrE4hVyQZA3KS6u8cfHD1woEoTsJKDp8vLyx5aIcSmRRr+BgzrmX9ObDw+GojE=,iv:JK/Cc9nMxnCetNqwquROKvw8TGMorwx42t5x622FL8M=,tag:jjaUEpNv94GmPIO1hAhZUA==,type:str]
  pgp:
    - created_at: "2025-04-29T08:35:20Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DM8dcuKjdXWESAQdAT7GOHRIebTH29lXYsf62qAICZDEbUU1PG75eAvb16Qsw
        25O9od88VcGb5eqiJt6wIjpQPxK1Y5kOz9JmYUPYu1pAPS5+67gdwG01VOj5gB4S
        0l4BuLz28RU39K9EP01p0Iss0AGy/CXhM5qAtK7bGCO2PAQuUTpv/lwy+0FNMzHR
        sd8bGIMB366Of7jVXFuCOGA80cUSkspkvQcrvhtEso0UGD0K9paCVdg6azz3Ox/8
        =UMlR
        -----END PGP MESSAGE-----
      fp: 4D6B62168F6FFE33B8420BCBED7FCB814CB6C157
  unencrypted_suffix: _unencrypted
  version: 3.10.2
