hashed_passwords:
  bmr: ENC[AES256_GCM,data:R0pUMhWvuPf3tQ3K7JbuCq5nvezlIMeoi/nLvuAbz+/fWWmWv63mZQkxf8ibNxoXSVvgzM7nfN+1dKjvoZKoHd+kZ/5S+ZER4g==,iv:uCRG/m4DGUY5+6AXB0AXFdIPf3nfT2Z/fdCKvWvqOKE=,tag:+nqxmqYaWEsrhm4mW/irWA==,type:str]
  root: ENC[AES256_GCM,data:Gdt8ufKKhR0QPPAgojdgWCZ8lrInhJ1d29p6xhoIOM1t2WPTQ/yLFQLZyacIwx7+cKQ5KwSdn/Hi/C4vI9jkP/6oLoufFk5s4A==,iv:y5fKwle4S0AQf+wr810M87TsQNV7CvKiqdSr3IHhUNM=,tag:6sx1E1oTZvzad4hZE4VK5w==,type:str]
sops:
  age:
    - recipient: age1wadrydzchtpz9flzy7geszrcupald64v9zl8cyr2e2r2cr8rwgxq0lvfjg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM2twUjFVMXVKem8vcXEy
        MlFlMHMvOEFFTEhWQkZnQVkxeDUxTmh6N1NJCnB2Z2syWGJnS3dNSlRFR2ZtbFdM
        ZzRqd2dSMmR4Q2dCOVBCUjdKK1RlaUkKLS0tIEdwSllJRDlXY0hqSm81eHk3U0tN
        aHpRK0hPNVJqMEVtSFova3FiVkJVWWcKudtvtvO5kzfV/TrgeT9l7J9zAy6r5pJ7
        ay99TjkPyw9ihd0TvUDBxgq8Ky0P2iMCE+5bQohAyUv0bKpz9R8M7Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1tpm1qg43j96890nswz990yhfsdtn7n5lh2xcxjxpxnrwu8x328wzkh6e287ug0x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHRwbS1lY2MgN0RzMG5nIEF6SmlRYkR2
        QTVKcUF2Ykc2c3M4dXN5bEFIdWgrM2V4K0ZXSSt0SUR1OWdOCmFhZHVmRHo2MVQv
        YnNjeDltUmlYd1UwV2sxdWlsVU4wVlB1YUVSQnJWeHcKLS0tIHNjR0xHUC80YTA0
        d1FMamVlbHcxMmJzeVo1MUpYUjRQN1V5ZXB3SGpUdFEKCmRYDjeeeSDEer2EUTvh
        t1e021wy+SshYhzHzcMQH4ctnf2qXXNIUyHyNuUWF2EcqMhKRNmN+HxxItBPdQsF
        9Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1jyazkguk47p46qaatr6avlexslu7amfra690f7jpwq55l2t6p5hqz67q7j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQXpHTnExTHRnUW55UDVY
        MU9EOUo4RmN3VXhNQ0IrTzFBUDlxMmxGRGhJCmpmNGN1NlRTUEhNMzdQenRjZytB
        bEhkeXhIL2RTTWp6Q3hwZUU2amgxTVUKLS0tIE1iSjlxQ0hkL2JBZE9vRG5zWkt4
        WVdjeWxyVGw5ZDhoSE9xd09HUEdJdFEKaSZ7H5Cqnkw/fNwB2mrhZDtlgVMo8Ty/
        xgq+cuy2Fujk17ABoJVIa0F0Um4DL1vxSkf7zYYBNKoIxh5Yu7i22Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-13T18:27:09Z"
  mac: ENC[AES256_GCM,data:pHO5UK7++f6FS+Ahv/w/Bn9ptF1v5knL3Yq+s/XdukmTR7vc1yuJx8K0o6DyeThzfP3iciBtPf5HWcnmi8fdevqET/WhDMisPR42QR34IeoYgwHBZd8zgSVuGDP4aTK5jJBBIzU9Xc+dYORtwyJdI0/nLQVQwiGakP2mgZ2qD3U=,iv:XWNsWLJZdUvuOLpz2KAr9y7RXblqEur3RNP3CEW+t2A=,tag:9DjoqBeDhmrDzbF7NMpZXw==,type:str]
  pgp:
    - created_at: "2025-08-13T11:00:12Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DM8dcuKjdXWESAQdAuNbMHMeg7UmEaUYK4eVE+Tt8NKfyWGSpmXrphljfz1Uw
        nSMzyqGM0q4N+4hjOpeZVvHfdYFGqd7YiEt+H00Ve8BokNH6oDwAGQUbdj/nfxwD
        0l4BlnsJNPypN+/cukgr+ggRmx2UDZWjHMtWwni6NlW07zSDF/d5k18CAU2hmuqB
        bkbGr+wNg7Cm2w40FmSxtoKwPGkrrJOjcC6A4Wx/ZDQiFLRIC05Dyi/RqNBZTy9d
        =nkKY
        -----END PGP MESSAGE-----
      fp: 4D6B62168F6FFE33B8420BCBED7FCB814CB6C157
  unencrypted_suffix: _unencrypted
  version: 3.10.2
