hashed_password: ENC[AES256_GCM,data:0kjAHHrW0LUoG2TKVqivtsSliJ/h82gvNldmIh/yutvwIwt+9QQ8kUW+/fCkBrdiw+smmTEZz805aARhAXQV6dXOSJjHvfqE0g==,iv:mxh18ezy2mMf8E2/h1voj5xbap69XsZUBY2xN6IOFsA=,tag:MT8UVMVNeFe4suKzyQ9RXg==,type:str]
networks: ENC[AES256_GCM,data:LMwfRq2TtwExt7HL+SepZxXDp4k26qtYjgyw4kySnc6VzuUo0u7MQf4hpUpJDOWRnvoEzhifnPTSopn6HKCi8YWSkD1RUZOjmkGc1MjrZho61FxAOMkxj2k0DHtw2IvUEvXBR50/TaYAB1cxIXSKRKbcru3R0a3wOnzngBvtDg==,iv:FCYJmkM8PxSmEEoJeVop93lJmbXraXUbg57xoOyXf/c=,tag:RJjwbALpx5MFKICLZtXX9A==,type:str]
sops:
  age:
    - recipient: age1wadrydzchtpz9flzy7geszrcupald64v9zl8cyr2e2r2cr8rwgxq0lvfjg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSFhERDREcVJpdXUwMEFK
        T0cvYS8yQXhCUEgwbnRmUnNPYlV0U0pnWWljCnl4TFpjN0pXZ0llTlRRekpPRW9X
        YktCTnpsa1FMVDNTZjc0VmxlV3lSUlUKLS0tIEdxZitnWDAyTFBFRWRaK3E4c25O
        R20xdTNNYUtsd0ZPYWlXWVNWS0VsU0EKszjohFNt62FlJpiVhPJ+woVcpeU3Qs1j
        53Syk2/Quoq2cVagvLNYdMPOzBVDKToj2slGzc0o4OWq9P7I0WFExg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1jyazkguk47p46qaatr6avlexslu7amfra690f7jpwq55l2t6p5hqz67q7j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUGFvdktMK1ZEcjBtTHpD
        aWNSUkUrcTgzTCs4c3dxV1FDMnJsa2ljRWd3CmVIak1wZm9nTnI2UlU1N0JzT0py
        NnQ4eXFNaGpIZWJzT3dzNjJNWVBiMUUKLS0tIHZXUXNFUE9sbU9VTzcvTWlwVDFm
        MHZ6Snd4c29WdWIxOUQ3MG85TjFUN00KzkGLjK/wySG5QOo9l39asySqZ4NDaO77
        Kly/8sVBMyfsQynydYoOFYwQ7jEXaHDYQMY52KVgTVObCUXLp6s12g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-19T07:40:14Z"
  mac: ENC[AES256_GCM,data:Z3rKMHy5WBgvnnY+Q4PR4lOzdEullQ5h68o1Tu0UUg2bpDz37KzpBayXeY281Q0aIHM/b0R4ZQygDD76vrtn0csRGBKQVzwtnwOm1XcV4A5e8w68gpImCXEkbYsVR8mj+cTp7yfBM7jYxkopKonnTvv14XxCXl45cuG+7UyUVpM=,iv:ZQsDjdKNs3Gnl4i/155pqIeXsWKKgRigu+/OWg219rA=,tag:X1djt6wMdPwwBFKsJVCxuA==,type:str]
  pgp:
    - created_at: "2026-03-11T11:44:10Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hH4DJBGmhVjpZEASAgMEVttjqqbkhSOoHWteoqK1VMmEZmWFuQVHU8sFwdnEbecA
        6ZWxU1Mf+46WdwtD5po6ocTNZwrdoCDt25Rhx1xocTBL8ZyOib9h2Lnjo50jJ3xL
        PR9nhY/XUEMipF/veNEvS9ZBSHgz0TxP0j/ubHYWOurSXgF0ey3YJOKpu/GFFbmj
        8jOqaCRMn7AzZd2eFqbykVIS5rsW024j+GilkPkWdJZXxsFld06PtsDYlLEDD2Ov
        AV34dCalfDiRRT1S7xx7cjxQPBZpXLMt78vebJkxSMw=
        =7qyQ
        -----END PGP MESSAGE-----
      fp: 744A942D0348D4EC23F9339FE5231FEFFA0D518C
  unencrypted_suffix: _unencrypted
  version: 3.10.2
