[
  ./home.nix
  ./programs/fzf-tab-completion.nix
  ./programs/gcc.nix
  ./programs/goto.nix
  ./programs/grep.nix
  ./programs/keepassxc.nix
  ./programs/keepassxc.nix
  ./programs/konsole.nix
  ./programs/kubectl.nix
  ./programs/less.nix
  ./programs/plasma.nix
  ./programs/shellcheck.nix
  ./programs/signal-desktop.nix
  ./programs/slack.nix
  ./programs/taskell.nix
  ./programs/yamllint.nix
  ./programs/zsh.nix
  ./xdg.nix
]
