name: neovim
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Check format with stylua
        uses: JohnnyMorganz/stylua-action@v2
        with:
          args: --config-path=.config/nvim/stylua.toml --check .
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
