jobs:
  nix-flake-check:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - name: Create passwords database stub for the installer image
        run: 'sudo mkdir -p /home/bmr/Documents

          sudo touch /home/bmr/Documents/passwords.kdbx

'
      - name: Check flake
        run: nix flake check --print-build-logs --impure
name: Evaluate the flake and run its checks
'on': push
